
name: 加密解密工具

on:
  workflow_dispatch:
    inputs:
      text:
        description: '原文'
        required: true
      environment:
        description: '哪个环境'
        type: environment
        required: true
jobs:
  show:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: | 
          echo $ENCRYPTION_KEY | wc -m
          echo $INPUT_TEXT
        env: 
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          
       
